inherit:
    - ../base.yaml

training:
    task_name: sparse_linear_regression
    sparsity: 3
    curriculum:
        points:
            start: 11
            end: 41
            inc: 2

out_dir: ./results2/sparse_LR_baseline
debug_mode: False