wandb:
    project: Lets_Loop2
    notes: looped tf 1 layer b = 10 L = 4
    log_every_steps: 100

gpu:
    cuda: True
    n_gpu: 0

model:
    family: gpt2_loop
    n_embd: 256
    n_layer: 4
    n_head: 4
    n_dims: 10
    n_positions: 101
    last_n_tokens: null


training:
    seed: null
    batch_size: 64
    task_name: linear_regression
    learning_rate: 0.0001
    weight_decay: 0.0
    train_steps: 20000
    save_every_steps: 1000
    keep_every_steps: 100000
    curriculum:
        dims:
            start: 10
            end: 10
            inc: 0
            interval: 10000
        points:
            start: 31
            end: 31
            inc: 0
            interval: 10000
        loops:
            start: 10
            end: 10
            inc: 0
            interval: 500
    n_loop_window: 20

out_dir: ./results2/linear_regression_loop
debug_mode: False