wandb:
    project: Lets_Loop2
    notes: exp_1__n_dims_8_points_41__loop_30_layers2__vs__loop_1_layers12
    log_every_steps: 100

gpu:
    cuda: True

model:
    family: gpt2_loop
    n_embd: 256
    n_layer: 1
    n_head: 8
    n_dims: 8
    n_positions: 101

training:
    batch_size: 64
    task_name: linear_regression
    learning_rate: 0.0001
    weight_decay: 0.0
    train_steps: 20000
    save_every_steps: 1000
    keep_every_steps: 100000
    curriculum:
        dims:
            start: 8
            end: 8
            inc: 0
            interval: 10000
        points:
            start: 41
            end: 41
            inc: 0
            interval: 10000
        loops:
            start: 30
            end: 30
            inc: 0
            interval: 500
    n_loop_window: 20

out_dir: ./results2/linear_regression_loop
debug_mode: False