inherit:
    - ../base_loop.yaml

training:
    task_name: relu_2nn_regression
    curriculum:
        points:
            start: 26
            end: 101
            inc: 5

out_dir: ./results2/relu_2nn_loop
debug_mode: False