inherit:
    - ../base_loop.yaml

model:
    pred_type: classification

training:
    curriculum:
        points:
            start: 11
            end: 41
            inc: 2

out_dir: ./results2/openml_loop
debug_mode: False