wandb:
    project: Lets_Loop2
    notes: exp_1__n_dims_8_points_41__loop_5_layers2__vs__loop_1_layers12
    log_every_steps: 100

gpu:
    cuda: True

model:
    family: gpt2_loop
    n_embd: 256
    n_layer: 1
    n_head: 4
    n_dims: 10
    n_positions: 101

training:
    batch_size: 64
    task_name: linear_regression
    learning_rate: 0.0001
    weight_decay: 0.0
    train_steps: 10000
    save_every_steps: 1000
    keep_every_steps: 10000
    curriculum:
        dims:
            start: 10
            end: 10
            inc: 0
            interval: 10000
        points:
            start: 21
            end: 21
            inc: 0
            interval: 10000
        loops:
            start: 1
            end: 1
            inc: 0
            interval: 500
    n_loop_window: 20

out_dir: ./results2/linear_regression_loop
debug_mode: False