wandb:
    project: Lets_Loop2
    notes:
    log_every_steps: 100

gpu:
    cuda: True

model:
    family: gpt2
    n_embd: 256
    n_layer: 12
    n_head: 8
    n_dims: 10
    n_positions: 201

training:
    batch_size: 64
    task_name: linear_regression
    learning_rate: 0.0001
    weight_decay: 0.0
    train_steps: 200000
    save_every_steps: 1000
    keep_every_steps: 100000
    curriculum:
        dims:
            start: 5
            end: 10
            inc: 1
            interval: 10000
        points:
            start: 11
            end: 21
            inc: 2
            interval: 10000
        loops:
            start: 1
            end: 1
            inc: 2
            interval: 500
    n_loop_window: 20

out_dir: ./results2/linear_regression_baseline
debug_mode: False