wandb:
    project: Lets_Loop2
    notes:
    log_every_steps: 100

gpu:
    cuda: True

model:
    family: gpt2_loop
    n_embd: 256
    n_layer: 1
    n_head: 8
    n_dims: 20
    n_positions: 101

training:
    batch_size: 64
    task_name: linear_regression
    learning_rate: 0.0001
    weight_decay: 0.0
    train_steps: 500000
    save_every_steps: 1000
    keep_every_steps: 100000
    curriculum:
        dims:
            start: 5
            end: 20
            inc: 1
            interval: 5000
        points:
            start: 11
            end: 41
            inc: 2
            interval: 5000
        loops:
            start: 20
            end: 350
            inc: 2
            interval: 500
    n_loop_window: 20

out_dir: ./results2/linear_regression_loop
debug_mode: False