wandb:
    project: Lets_Loop2
    notes: constant_dims_10
    log_every_steps: 100

gpu:
    cuda: True

model:
    family: gpt2
    n_embd: 256
    n_layer: 12
    n_head: 8
    n_dims: 8
    n_positions: 101

training:
    batch_size: 64
    task_name: linear_regression
    learning_rate: 0.0001
    weight_decay: 0.0
    train_steps: 50000
    save_every_steps: 1000
    keep_every_steps: 10000
    curriculum:
        dims:
            start: 8
            end: 8
            inc: 0
            interval: 6000
        points:
            start: 41
            end: 41
            inc: 0
            interval: 6000
        loops:
            start: 1
            end: 1
            inc: 2
            interval: 500
    n_loop_window: 20

out_dir: ./results2/linear_regression_baseline
debug_mode: False